// This file is auto-generated by Tuono

import { createRoute, __tuono__internal__lazyLoadRoute } from 'tuono'

import RootLayoutImport from './routes/layout'

const PostsLayoutImport = __tuono__internal__lazyLoadRoute(
  () => import('./routes/posts/layout'),
)
const PageImport = __tuono__internal__lazyLoadRoute(
  () => import('./routes/page'),
)
const PostsPageImport = __tuono__internal__lazyLoadRoute(
  () => import('./routes/posts/page'),
)
const AboutPageImport = __tuono__internal__lazyLoadRoute(
  () => import('./routes/about/page'),
)
const PostsMyPostPageImport = __tuono__internal__lazyLoadRoute(
  () => import('./routes/posts/my-post/page'),
)
const PostspostPageImport = __tuono__internal__lazyLoadRoute(
  () => import('./routes/posts/[post]/page'),
)

const rootRoute = createRoute({
  isRoot: true,
  component: RootLayoutImport,
  dataKey: '/layout',
})

const PostsLayout = createRoute({ component: PostsLayoutImport, isRoot: true })
const Page = createRoute({ component: PageImport })
const PostsPage = createRoute({ component: PostsPageImport })
const AboutPage = createRoute({ component: AboutPageImport })
const PostsMyPostPage = createRoute({ component: PostsMyPostPageImport })
const PostspostPage = createRoute({ component: PostspostPageImport })

// Create/Update Routes

const PostsLayoutRoute = PostsLayout.update({
  getParentRoute: () => rootRoute,
  filePath: '/posts/layout',
  dataKey: '/posts/layout',
})

const PageRoute = Page.update({
  path: '/',
  getParentRoute: () => rootRoute,
  filePath: '/',
  dataKey: '/page',
})

const PostsPageRoute = PostsPage.update({
  path: '/posts',
  getParentRoute: () => PostsLayoutRoute,
  filePath: '/posts/',
  dataKey: '/posts/page',
})

const AboutPageRoute = AboutPage.update({
  path: '/about',
  getParentRoute: () => rootRoute,
  filePath: '/about/',
  dataKey: '/about/page',
})

const PostsMyPostPageRoute = PostsMyPostPage.update({
  path: '/posts/my-post',
  getParentRoute: () => PostsLayoutRoute,
  filePath: '/posts/my-post/',
  dataKey: '/posts/my-post/page',
})

const PostspostPageRoute = PostspostPage.update({
  path: '/posts/[post]',
  getParentRoute: () => PostsLayoutRoute,
  filePath: '/posts/[post]/',
  dataKey: '/posts/[post]/page',
})

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  PageRoute,
  PostsLayoutRoute.addChildren([
    PostsPageRoute,
    PostspostPageRoute,
    PostsMyPostPageRoute,
  ]),
  AboutPageRoute,
  PostsPageRoute,
  PostspostPageRoute,
  PostsMyPostPageRoute,
])
