[workspace]
resolver = "2"
members = [
  "crates/ossido_cli",
  "crates/ossido_internal",
  "crates/ossido",
  "crates/ossido_macros",
  "crates/ossido_ssr"
]
exclude = [
  "examples/with-mdx",
  "examples/ossido-app",
  "examples/ossido-tutorial",
  "examples/with-tailwind",
  "e2e/fixtures/base",
]