edition = "2024"

[workspace]
resolver = "2"
members = [
  "crates/ossido", 
  "crates/ossido_internal", 
  "crates/ossido_lib", 
  "crates/ossido_lib_macros"
]
exclude = [
  "examples/with-mdx",
  "examples/ossido-app",
  "examples/ossido-tutorial",
  "examples/with-tailwind",
  "e2e/fixtures/base",
]