// File automatically generated by ossido
// Do not manually update this file
import 'vite/modulepreload-polyfill';
import { hydrate } from 'ossido/hydration';

// Import the generated route tree
import { routeTree } from './routeTree.gen';

hydrate(routeTree);
