// File automatically generated by ossido
// Do not manually update this file
import 'vite/modulepreload-polyfill';
import {
  hydrate,
  __ossido__internal__devServerRestarting,
  __ossido__internal__devServerReady,
  __ossido__internal__recordFullReload,
} from '@ossido-labs/ossido/hydration';

// Import the generated route tree
import { routeTree } from './routeTree.gen';

hydrate(routeTree);

// Dev only (`import.meta.hot` is falsy in prod, so this block — and the dev
// hooks it references — are eliminated from the production bundle):
// - `ossido:rust-restarting` / `ossido:rust-ready` are sent by `ossido dev`
//   around a Rust server rebuild; "ready" re-fetches the current route's
//   server props in place, so a `page.rs` / `layout.rs` edit updates the page
//   without a full reload.
// - `vite:beforeFullReload` records what caused a hard reload, surfaced by the
//   dev indicator after the page comes back.
if (import.meta.hot) {
  import.meta.hot.on(
    'ossido:rust-restarting',
    __ossido__internal__devServerRestarting,
  );
  import.meta.hot.on('ossido:rust-ready', __ossido__internal__devServerReady);
  import.meta.hot.on('vite:beforeFullReload', __ossido__internal__recordFullReload);
}
