// This file is auto-generated by Tuono

import { createRoute, __tuono__internal__lazyLoadRoute } from 'tuono'

import RootLayoutImport from './routes/layout'

const PageImport = __tuono__internal__lazyLoadRoute(
  () => import('./routes/page'),
)
const AboutPageImport = __tuono__internal__lazyLoadRoute(
  () => import('./routes/about/page'),
)
const PostsMyPostPageImport = __tuono__internal__lazyLoadRoute(
  () => import('./routes/posts/my-post/page'),
)

const rootRoute = createRoute({
  isRoot: true,
  component: RootLayoutImport,
  dataKey: '/layout',
})

const Page = createRoute({ component: PageImport })
const AboutPage = createRoute({ component: AboutPageImport })
const PostsMyPostPage = createRoute({ component: PostsMyPostPageImport })

// Create/Update Routes

const PageRoute = Page.update({
  path: '/',
  getParentRoute: () => rootRoute,
  filePath: '/',
  dataKey: '/page',
})

const AboutPageRoute = AboutPage.update({
  path: '/about',
  getParentRoute: () => rootRoute,
  filePath: '/about/',
  dataKey: '/about/page',
})

const PostsMyPostPageRoute = PostsMyPostPage.update({
  path: '/posts/my-post',
  getParentRoute: () => rootRoute,
  filePath: '/posts/my-post/',
  dataKey: '/posts/my-post/page',
})

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  PageRoute,
  AboutPageRoute,
  PostsMyPostPageRoute,
])
