// This file is auto-generated by Ossido

import {
  createRoute,
  __ossido__internal__lazyLoadRoute,
  __ossido__internal__applyRouteHot,
} from 'ossido'

import RootLayoutImport from './routes/layout'

const PostsLayoutImport = __ossido__internal__lazyLoadRoute(
  () => import('./routes/posts/layout'),
)
const PageImport = __ossido__internal__lazyLoadRoute(
  () => import('./routes/page'),
)
const PostsPageImport = __ossido__internal__lazyLoadRoute(
  () => import('./routes/posts/page'),
)
const AboutPageImport = __ossido__internal__lazyLoadRoute(
  () => import('./routes/about/page'),
)
const PostsMyPostPageImport = __ossido__internal__lazyLoadRoute(
  () => import('./routes/posts/my-post/page'),
)
const PostspostPageImport = __ossido__internal__lazyLoadRoute(
  () => import('./routes/posts/[post]/page'),
)

const rootRoute = createRoute({
  isRoot: true,
  component: RootLayoutImport,
  dataKey: '/layout',
})

const PostsLayout = createRoute({ component: PostsLayoutImport, isRoot: true })
const Page = createRoute({ component: PageImport })
const PostsPage = createRoute({ component: PostsPageImport })
const AboutPage = createRoute({ component: AboutPageImport })
const PostsMyPostPage = createRoute({ component: PostsMyPostPageImport })
const PostspostPage = createRoute({ component: PostspostPageImport })

// Create/Update Routes

const PostsLayoutRoute = PostsLayout.update({
  getParentRoute: () => rootRoute,
  filePath: '/posts/layout',
  dataKey: '/posts/layout',
})

const PageRoute = Page.update({
  path: '/',
  getParentRoute: () => rootRoute,
  filePath: '/',
  dataKey: '/page',
})

const PostsPageRoute = PostsPage.update({
  path: '/posts',
  getParentRoute: () => PostsLayoutRoute,
  filePath: '/posts/',
  dataKey: '/posts/page',
})

const AboutPageRoute = AboutPage.update({
  path: '/about',
  getParentRoute: () => rootRoute,
  filePath: '/about/',
  dataKey: '/about/page',
})

const PostsMyPostPageRoute = PostsMyPostPage.update({
  path: '/posts/my-post',
  getParentRoute: () => PostsLayoutRoute,
  filePath: '/posts/my-post/',
  dataKey: '/posts/my-post/page',
})

const PostspostPageRoute = PostspostPage.update({
  path: '/posts/[post]',
  getParentRoute: () => PostsLayoutRoute,
  filePath: '/posts/[post]/',
  dataKey: '/posts/[post]/page',
})

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  PageRoute,
  PostsLayoutRoute.addChildren([
    PostsPageRoute,
    PostspostPageRoute,
    PostsMyPostPageRoute,
  ]),
  AboutPageRoute,
  PostsPageRoute,
  PostspostPageRoute,
  PostsMyPostPageRoute,
])

if (import.meta.hot) {
  import.meta.hot.accept(
    [
      './routes/layout',
      './routes/posts/layout',
      './routes/page',
      './routes/posts/page',
      './routes/about/page',
      './routes/posts/my-post/page',
      './routes/posts/[post]/page',
    ],
    ([m0, m1, m2, m3, m4, m5, m6]) => {
      __ossido__internal__applyRouteHot(() => {
        if (m0) {
          rootRoute.component = m0.default
        }
        if (m1) {
          PostsLayoutImport.update(m1.default)
        }
        if (m2) {
          PageImport.update(m2.default)
        }
        if (m3) {
          PostsPageImport.update(m3.default)
        }
        if (m4) {
          AboutPageImport.update(m4.default)
        }
        if (m5) {
          PostsMyPostPageImport.update(m5.default)
        }
        if (m6) {
          PostspostPageImport.update(m6.default)
        }
      })
    },
  )
}
