services:
  ossido:
    platform: linux/amd64
    container_name: ossido-source-container
    hostname: ossido-source-container
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        RUST_VERSION: 1.88 # if change, think to update the default ARGs in Dockerfile
        BASE_OS: bookworm # if change, think to update the default ARGs in Dockerfile
    image: ossido-source-image
    ports:
      - '3000:3000' # expose default port used by ossido server
    volumes: # mount the project into a volume but node_modules / target / ... directories won't by sync from container to host
      - ..:/ossido
      - /ossido/node_modules
      - /ossido/target
      - /ossido/.turbo
      - /ossido/examples/ossido-app/node_modules
      - /ossido/examples/ossido-app/target
      - /ossido/examples/ossido-tutorial/node_modules
      - /ossido/examples/ossido-tutorial/target
      - /ossido/examples/with-mdx/node_modules
      - /ossido/examples/with-mdx/target
    tty: true
