// File automatically generated by tuono
// Do not manually update this file
import { serverSideRendering } from 'tuono/ssr'

import { routeTree } from './routeTree.gen'

const renderer = serverSideRendering(routeTree)

// Buffered render (error pages, static export, dev fallback) and streaming
// render (progressive page responses) are exposed as separate named exports so
// the Rust runtime can call each by name (`renderFn` / `renderStream`).
export const renderFn = renderer.renderFn
export const renderStream = renderer.renderStream
