// This file is auto-generated by Tuono

import { createRoute, __tuono__internal__lazyLoadRoute } from 'tuono'

import RootLayoutImport from './routes/layout'

const PageImport = __tuono__internal__lazyLoadRoute(
  () => import('./routes/page'),
)
const AboutPageImport = __tuono__internal__lazyLoadRoute(
  () => import('./routes/about/page.mdx'),
)

const rootRoute = createRoute({
  isRoot: true,
  component: RootLayoutImport,
  dataKey: '/layout',
})

const Page = createRoute({ component: PageImport })
const AboutPage = createRoute({ component: AboutPageImport })

// Create/Update Routes

const PageRoute = Page.update({
  path: '/',
  getParentRoute: () => rootRoute,
  filePath: '/',
  dataKey: '/page',
})

const AboutPageRoute = AboutPage.update({
  path: '/about',
  getParentRoute: () => rootRoute,
  filePath: '/about/',
  dataKey: '/about/page',
})

// Create and export the route tree

export const routeTree = rootRoute.addChildren([PageRoute, AboutPageRoute])
