// This file is auto-generated by Tuono

import { createRoute, __tuono__internal__lazyLoadRoute } from 'tuono'

import RootLayoutImport from './routes/layout'

const PageImport = __tuono__internal__lazyLoadRoute(
  () => import('./routes/page'),
)
const PostscatchallPageImport = __tuono__internal__lazyLoadRoute(
  () => import('./routes/posts/[...catch_all]/page'),
)

const rootRoute = createRoute({
  isRoot: true,
  component: RootLayoutImport,
  dataKey: '/layout',
})

const Page = createRoute({ component: PageImport })
const PostscatchallPage = createRoute({ component: PostscatchallPageImport })

// Create/Update Routes

const PageRoute = Page.update({
  path: '/',
  getParentRoute: () => rootRoute,
  filePath: '/',
  dataKey: '/page',
})

const PostscatchallPageRoute = PostscatchallPage.update({
  path: '/posts/[...catch_all]',
  getParentRoute: () => rootRoute,
  hasHandler: true,
  filePath: '/posts/[...catch_all]/',
  dataKey: '/posts/[...catch_all]/page',
})

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  PageRoute,
  PostscatchallPageRoute,
])
