[package]
name = "ossido_macros"
version = "0.1.0"
edition = "2024"
description = "Superfast React fullstack framework"
homepage = "https://ossido.dev"
keywords = [ "react", "typescript", "fullstack", "web", "ssr"]
repository = "https://github.com/ossido-labs/ossido"
readme = "../../README.md"
license-file = "../../LICENSE.md"
categories = ["web-programming"]
include = [
		"src/**/*.rs",
		"Cargo.toml"
]

[lib]
proc-macro = true

[dependencies]
syn = { version = "3.0.3", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
