// This file is auto-generated by Tuono

import { createRoute, __tuono__internal__lazyLoadRoute } from 'tuono'

import RootLayoutImport from './routes/layout'

import ErrorImport from './routes/error'
import LoadingImport from './routes/loading'
import PostsLoadingImport from './routes/posts/loading'

const PageImport = __tuono__internal__lazyLoadRoute(
  () => import('./routes/page'),
)
const PostsPageImport = __tuono__internal__lazyLoadRoute(
  () => import('./routes/posts/page'),
)
const AboutPageImport = __tuono__internal__lazyLoadRoute(
  () => import('./routes/about/page'),
)
const PostspostPageImport = __tuono__internal__lazyLoadRoute(
  () => import('./routes/posts/[post]/page'),
)

const rootRoute = createRoute({
  isRoot: true,
  component: RootLayoutImport,
  dataKey: '/layout',
})

const Page = createRoute({ component: PageImport })
const PostsPage = createRoute({ component: PostsPageImport })
const AboutPage = createRoute({ component: AboutPageImport })
const PostspostPage = createRoute({ component: PostspostPageImport })

// Create/Update Routes

const PageRoute = Page.update({
  path: '/',
  getParentRoute: () => rootRoute,
  filePath: '/',
  dataKey: '/page',
  loadingComponent: LoadingImport,
  errorComponent: ErrorImport,
})

const PostsPageRoute = PostsPage.update({
  path: '/posts',
  getParentRoute: () => rootRoute,
  filePath: '/posts/',
  dataKey: '/posts/page',
  loadingComponent: PostsLoadingImport,
  errorComponent: ErrorImport,
})

const AboutPageRoute = AboutPage.update({
  path: '/about',
  getParentRoute: () => rootRoute,
  filePath: '/about/',
  dataKey: '/about/page',
  loadingComponent: LoadingImport,
  errorComponent: ErrorImport,
})

const PostspostPageRoute = PostspostPage.update({
  path: '/posts/[post]',
  getParentRoute: () => rootRoute,
  filePath: '/posts/[post]/',
  dataKey: '/posts/[post]/page',
  loadingComponent: PostsLoadingImport,
  errorComponent: ErrorImport,
})

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  PageRoute,
  AboutPageRoute,
  PostsPageRoute,
  PostspostPageRoute,
])
