// This file is auto-generated by Tuono

import { createRoute, __tuono__internal__lazyLoadRoute } from 'tuono'

import RootLayoutImport from './routes/__layout'

import ErrorImport from './routes/error'
import LoadingImport from './routes/loading'
import PostsLoadingImport from './routes/posts/loading'

const AboutImport = __tuono__internal__lazyLoadRoute(
  () => import('./routes/about'),
)
const IndexImport = __tuono__internal__lazyLoadRoute(
  () => import('./routes/index'),
)
const PostspostImport = __tuono__internal__lazyLoadRoute(
  () => import('./routes/posts/[post]'),
)
const PostsIndexImport = __tuono__internal__lazyLoadRoute(
  () => import('./routes/posts/index'),
)

const rootRoute = createRoute({ isRoot: true, component: RootLayoutImport })

const About = createRoute({ component: AboutImport })
const Index = createRoute({ component: IndexImport })
const Postspost = createRoute({ component: PostspostImport })
const PostsIndex = createRoute({ component: PostsIndexImport })

// Create/Update Routes

const AboutRoute = About.update({
  path: '/about',
  getParentRoute: () => rootRoute,
  filePath: '/about',
  loadingComponent: LoadingImport,
  errorComponent: ErrorImport,
})

const IndexRoute = Index.update({
  path: '/',
  getParentRoute: () => rootRoute,
  filePath: '/',
  loadingComponent: LoadingImport,
  errorComponent: ErrorImport,
})

const PostspostRoute = Postspost.update({
  path: '/posts/[post]',
  getParentRoute: () => rootRoute,
  filePath: '/posts/[post]',
  loadingComponent: PostsLoadingImport,
  errorComponent: ErrorImport,
})

const PostsIndexRoute = PostsIndex.update({
  path: '/posts',
  getParentRoute: () => rootRoute,
  filePath: '/posts/',
  loadingComponent: PostsLoadingImport,
  errorComponent: ErrorImport,
})

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutRoute,
  PostsIndexRoute,
  PostspostRoute,
])
