[package]
name = "ossido_internal"
version = "0.1.0"
edition = "2024"
authors = ["Chris Schofield <chris@childishforces.com>"]
description = "Superfast React fullstack framework"
homepage = "https://ossido.dev"
keywords = [ "react", "typescript", "fullstack", "web", "ssr"]
repository = "https://github.com/ossido-labs/ossido"
readme = "../../README.md"
license-file = "../../LICENSE.md"
categories = ["web-programming"]
include = [
		"src/**/*.rs",
		"Cargo.toml"
]


[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.151"
colored = "3.1.1"
jiff = "0.2"

[dev-dependencies]
fs_extra = "1.3.0"
tempfile = "3.27.0"
assert_cmd = "2.2.2"
serial_test = "4.0.1"
