// This file is auto-generated by Ossido

import {
  createRoute,
  __ossido__internal__lazyLoadRoute,
  __ossido__internal__applyRouteHot,
} from '@ossido-labs/ossido';

import RootLayoutImport from './routes/layout';

import ErrorImport from './routes/error';
import LoadingImport from './routes/loading';
import PostsLoadingImport from './routes/posts/loading';

const PageImport = __ossido__internal__lazyLoadRoute(
  () => import('./routes/page'),
);
const PostsPageImport = __ossido__internal__lazyLoadRoute(
  () => import('./routes/posts/page'),
);
const AboutPageImport = __ossido__internal__lazyLoadRoute(
  () => import('./routes/about/page'),
);
const PostspostPageImport = __ossido__internal__lazyLoadRoute(
  () => import('./routes/posts/[post]/page'),
);

const rootRoute = createRoute({
  isRoot: true,
  component: RootLayoutImport,
  dataKey: '/layout',
});

const Page = createRoute({ component: PageImport });
const PostsPage = createRoute({ component: PostsPageImport });
const AboutPage = createRoute({ component: AboutPageImport });
const PostspostPage = createRoute({ component: PostspostPageImport });

// Create/Update Routes

const PageRoute = Page.update({
  path: '/',
  getParentRoute: () => rootRoute,
  filePath: '/',
  dataKey: '/page',
  loadingComponent: LoadingImport,
  errorComponent: ErrorImport,
});

const PostsPageRoute = PostsPage.update({
  path: '/posts',
  getParentRoute: () => rootRoute,
  filePath: '/posts/',
  dataKey: '/posts/page',
  loadingComponent: PostsLoadingImport,
  errorComponent: ErrorImport,
});

const AboutPageRoute = AboutPage.update({
  path: '/about',
  getParentRoute: () => rootRoute,
  filePath: '/about/',
  dataKey: '/about/page',
  loadingComponent: LoadingImport,
  errorComponent: ErrorImport,
});

const PostspostPageRoute = PostspostPage.update({
  path: '/posts/[post]',
  getParentRoute: () => rootRoute,
  filePath: '/posts/[post]/',
  dataKey: '/posts/[post]/page',
  loadingComponent: PostsLoadingImport,
  errorComponent: ErrorImport,
});

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  PageRoute,
  AboutPageRoute,
  PostsPageRoute,
  PostspostPageRoute,
]);

if (import.meta.hot) {
  import.meta.hot.accept(
    [
      './routes/layout',
      './routes/page',
      './routes/loading',
      './routes/error',
      './routes/posts/page',
      './routes/posts/loading',
      './routes/about/page',
      './routes/posts/[post]/page',
    ],
    ([m0, m1, m2, m3, m4, m5, m6, m7]) => {
      __ossido__internal__applyRouteHot(() => {
        if (m0) {
          rootRoute.component = m0.default;
        }
        if (m1) {
          PageImport.update(m1.default);
        }
        if (m2) {
          PageRoute.options.loadingComponent = m2.default;
          AboutPageRoute.options.loadingComponent = m2.default;
        }
        if (m3) {
          PageRoute.options.errorComponent = m3.default;
          PostsPageRoute.options.errorComponent = m3.default;
          AboutPageRoute.options.errorComponent = m3.default;
          PostspostPageRoute.options.errorComponent = m3.default;
        }
        if (m4) {
          PostsPageImport.update(m4.default);
        }
        if (m5) {
          PostsPageRoute.options.loadingComponent = m5.default;
          PostspostPageRoute.options.loadingComponent = m5.default;
        }
        if (m6) {
          AboutPageImport.update(m6.default);
        }
        if (m7) {
          PostspostPageImport.update(m7.default);
        }
      });
    },
  );
}
