// This file is auto-generated by Ossido

import {
  createRoute,
  __ossido__internal__lazyLoadRoute,
  __ossido__internal__applyRouteHot,
} from 'ossido';

import RootLayoutImport from './routes/layout';

const PageImport = __ossido__internal__lazyLoadRoute(
  () => import('./routes/page'),
);
const AboutPageImport = __ossido__internal__lazyLoadRoute(
  () => import('./routes/about/page'),
);
const PostsMyPostPageImport = __ossido__internal__lazyLoadRoute(
  () => import('./routes/posts/my-post/page'),
);

const rootRoute = createRoute({
  isRoot: true,
  component: RootLayoutImport,
  dataKey: '/layout',
});

const Page = createRoute({ component: PageImport });
const AboutPage = createRoute({ component: AboutPageImport });
const PostsMyPostPage = createRoute({ component: PostsMyPostPageImport });

// Create/Update Routes

const PageRoute = Page.update({
  path: '/',
  getParentRoute: () => rootRoute,
  filePath: '/',
  dataKey: '/page',
});

const AboutPageRoute = AboutPage.update({
  path: '/about',
  getParentRoute: () => rootRoute,
  filePath: '/about/',
  dataKey: '/about/page',
});

const PostsMyPostPageRoute = PostsMyPostPage.update({
  path: '/posts/my-post',
  getParentRoute: () => rootRoute,
  filePath: '/posts/my-post/',
  dataKey: '/posts/my-post/page',
});

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  PageRoute,
  AboutPageRoute,
  PostsMyPostPageRoute,
]);

if (import.meta.hot) {
  import.meta.hot.accept(
    [
      './routes/layout',
      './routes/page',
      './routes/about/page',
      './routes/posts/my-post/page',
    ],
    ([m0, m1, m2, m3]) => {
      __ossido__internal__applyRouteHot(() => {
        if (m0) {
          rootRoute.component = m0.default;
        }
        if (m1) {
          PageImport.update(m1.default);
        }
        if (m2) {
          AboutPageImport.update(m2.default);
        }
        if (m3) {
          PostsMyPostPageImport.update(m3.default);
        }
      });
    },
  );
}
